### ISSUE TITLE
Calculator blur effect doesn't work on Firefox.

### ISSUE THREAD

**Issue by MrHallway0** [PuruVJ/macos-web#103]
The blur effect for the calculator app doesn't display on Firefox.

## Firefox (Developer Edition 89.0b3)
![image](https://user-images.githubusercontent.com/65696362/115972753-1de68c00-a505-11eb-932c-33a7a319b0bb.png)

## Edge (90.0.818.46)
![image](https://user-images.githubusercontent.com/65696362/115972761-28088a80-a505-11eb-8477-69359357c2bb.png)

**Comment by PuruVJ** [comment]
Will have to wait until Firefox implements this ¯\\\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/47742487/115973279-650a6680-a571-11eb-9c87-424f2a4aa4c0.png)
