### ISSUE TITLE
package-lock.json and yarn.lock are ignored

### ISSUE THREAD

**Issue by nirtamir2** [PuruVJ/macos-web#111]
https://github.com/PuruVJ/macos-web/blob/main/.gitignore includes
```
package-lock.json
yarn.lock
```
It's better to commit them (choose one of them) and remove them from `.gitignore`.
This also causes issues with [codesandbox](https://codesandbox.io/s/github/PuruVJ/macos-web).
Why it's helpful? - see this https://stackoverflow.com/a/44904494/6708328.
From a personal perspective - installing the dependencies from remote may be different from your locally installed dependencies.

**Comment by PuruVJ** [comment]
Alright, will fix this

**Comment by PuruVJ** [comment]
For now, please use vite@2.2.4

**Comment by PuruVJ** [comment]
Alright, now I'm committing package lock. Try now

**Comment by PuruVJ** [comment]
Fixed in https://github.com/PuruVJ/macos-web/commit/0c747cb9793bd51c5dd866590fb5e2dc0061b5eec
