### ISSUE TITLE
Toggling Theme only works on clicking Moon Icons 🌖

### ISSUE THREAD

**Issue by saviomartin** [PuruVJ/macos-web#112]
Toggling of theme works only in clicking the moon icon, I think it would be better if the toggle function is placed on the component, that'll help if clicking on the text also. Have a look on this 💪

![icon](https://user-images.githubusercontent.com/61895712/119684390-16970300-be62-11eb-8d8a-21a5878a8edb.png)

**Comment by saviomartin** [comment]
Can I submit a PR on this?

**Comment by PuruVJ** [comment]
Closing this. Reason in https://github.com/PuruVJ/macos-web/pull/113
