### ISSUE TITLE
Magnification 

### ISSUE THREAD

**Issue by shaurya1709** [PuruVJ/macos-web#117]
The magnification effect should be disabled by default and made as a toggle.
In macOS Big Sur, the effect is not enabled by default. (the same with Monterey).

**Comment by PuruVJ** [comment]
Thanks, there is a reason why it is disabled.

However, this project is a mix of emulating macOS, while also showing off cool stuff, and the dock animations are mindblowing for everyone who sees them. So I'll keep them on by default.

However, I will ship a settings app to disable it, but that's far in the future. For near future I'll simply provide a toggle in the Action Center to turn off animations for folks with motion sickness and all.

Thanks for raising the issue
