### ISSUE TITLE
The meta data still says BigSur instead of Monterey

### ISSUE THREAD

**Issue by mrwatson-de** [PuruVJ/macos-web#28]
In the rendering in twitter I noticed that it describes the project as being of Big Sur, not Monterey ... Meta tag needs updating:

     <meta property="og:description" content="A painting of macOS Big Sur in HTML, CSS and JS">

**Comment by emmanuelkant** [comment]
This was resolved in this commit https://github.com/PuruVJ/macos-web/commit/26ffad16642608f703b2b81cdf0ea1186adb6277 so I think this should be closed.
