### ISSUE TITLE
Macos Dock problem

### ISSUE THREAD

**Issue by RedEdge967** [PuruVJ/macos-web#31]
# Hello Vijay
- I wanted to say, in 1024x600 resolution pc, when you click on other apps (like vscode) instead calculator, the dock is coming to the middle of the screen. and the apple menu disappear from the screen. like in the screenshot below 

## Screenshot
![Capture65](https://user-images.githubusercontent.com/91379432/148413946-7c70756c-c506-446d-aef5-63294d57ae5e.PNG)

**Comment by PuruVJ** [comment]
Hi, this issue should be fixed by now. Can you check again and confirm?

**Comment by RedEdge967** [comment]
Now it's okay. icons in the dock doesn't become bigger and the dock isn't coming to middle. Thank you!

![Capture67](https://user-images.githubusercontent.com/91379432/148676788-38bd9692-a32c-4852-9e9b-e8aeb2d0e93e.PNG)
