### ISSUE TITLE
Weird blurring

### ISSUE THREAD

**Issue by Lalit64** [PuruVJ/macos-web#4]
Hey, @PuruVJ I know this isn't meant to be a serious thing. But I found that the screen randomly blurs

<img width="339" alt="image" src="https://user-images.githubusercontent.com/79628080/129841092-5f1366cc-1299-4ebd-8c5c-ef2816ec7bd6.png">
Kinda like that

**Comment by PuruVJ** [comment]
Can you tell the browser and its version please?

**Comment by Lalit64** [comment]
Firefox Developer Edition 92.0b5 (64-bit)

**Comment by PuruVJ** [comment]
backdrop-filter is still experimental in Firefox, so these rendering bugs are inevitable. Only to fix these would be to wait for backdrop-filter to become stable.

**Comment by Lalit64** [comment]
Ok, Thanks
