### ISSUE TITLE
Feature Request: Use Apple's San Francisco instead of Inter

### ISSUE THREAD

**Issue by shaurya1709** [PuruVJ/macos-web#46]
# Request
Use San Francisco instead of Inter to make it closer to macOS.
# Links to the font
Regular (400): https://applesocial.s3.amazonaws.com/assets/styles/fonts/sanfrancisco/sanfranciscodisplay-regular-webfont.woff.
Bold (800): https://applesocial.s3.amazonaws.com/assets/styles/fonts/sanfrancisco/sanfranciscodisplay-bold-webfont.woff.

**Comment by PuruVJ** [comment]
I'm afraid it's proprietry, I'm not sure what will be the legal implications of pulling in the font, when their policy disallows anyone from using the font on web

**Comment by shaurya1709** [comment]
Yeah I forgot about that. May I close this issue?
