### ISSUE TITLE
Fix cursor

### ISSUE THREAD

**Issue by shaurya1709** [PuruVJ/macos-web#5]
The cursor looks extremely weird for macOS. I found an SVG file online for the cursor. [Link Here](http://cursor.in/assets/cursor.svg). Sorry for my language cause I'm 10.

**Comment by Nazeeh21** [comment]
Can I fix this?

**Comment by PuruVJ** [comment]
Sure! I haven't been able to get much time to fix these things, so would be great if you could make a PR

**Comment by Nazeeh21** [comment]
@shaurya1709  I am getting this error while running command  `npm run dev`

![image](https://user-images.githubusercontent.com/56908732/134017726-cf9777d4-4895-429d-8362-51c7323c041c.png)

**Comment by PuruVJ** [comment]
That's weird. You'd `cd`'ed into the root of the folder only, right?

**Comment by Nazeeh21** [comment]
Yes I do

**Comment by PuruVJ** [comment]
this has stayed inactive too long. Closing it
