### ISSUE TITLE
[Suggestion] - Iphone layout when opened in mobile device

### ISSUE THREAD

**Issue by cefasgarciapereira** [PuruVJ/macos-web#6]
I think it would be nice if the layout changed from mac to iphone when the app is openned in mobile devices or responsive mode on web.

**Comment by PuruVJ** [comment]
Hi

I have thought of this idea, and it isn't really very good, cuz it kinda defeats the purpose of the whole macos concept behind this project.

However, I have plan to make a standalone iOS for web. Stay tuned for that :)

**Comment by PuruVJ** [comment]
OFC, yur more than welcome to fork it and make it for your copy. I'll be more than happy to share that around if you do. A website that is macos in desktop and iOS in mobile? That's an enigma :)
