### ISSUE TITLE
Creating a Notes app

### ISSUE THREAD

**Issue by jaswch** [PuruVJ/macos-web#62]
Hi, I am having an issue that the notes app icon does not show up in the dock. 

![path](https://user-images.githubusercontent.com/10300504/209425014-2c9a36d3-7943-4c07-b5bf-3bcb93c4b793.png)

There is an app icon for the notes app in the public folder. Then I thought you need set it in the app configuration but I could not see any app or dock configuration file which sets the app icon on the dock.

![Problem](https://user-images.githubusercontent.com/10300504/209425086-d7569bd0-bbce-45ff-936d-6e9a41f1bb36.png)

**Comment by PuruVJ** [comment]
It shud be webp, not png

**Comment by jaswch** [comment]
Thank you

**Comment by jaswch** [comment]
but from these images could you please tell me which one I have to replace?

![Screenshot_select-area_20221224152025](https://user-images.githubusercontent.com/10300504/209430707-8fca7465-2435-46b1-bd3d-e38d2ace415e.png)

**Comment by PuruVJ** [comment]
256.png
