### ISSUE TITLE
traffic light icons on hover

### ISSUE THREAD

**Issue by Deep-Codes** [PuruVJ/macos-web#63]
You mostly know this, traffic lights show icons in hover state.

I tried implementing it looks like this

If you want this implemented let me know I would raise a PR on it.

![github](https://user-images.githubusercontent.com/61158210/114875539-02032c00-9e1b-11eb-9370-df9be909bc35.gif)

**Comment by PuruVJ** [comment]
OMG!!!! Thank you!!! please do make a PR 🤩🤩

**Comment by Deep-Codes** [comment]
https://github.com/PuruVJ/macos-web/blob/969df8a3223f5c012143fcd2e7a12b0c06621058/src/components/Desktop/Window/TrafficLights.tsx#L21

I believe here thougth they seem to be in order the naming is not correct:

```tsx
      <ButtonBase className={css.closeLight} onClick={closeApp} />
      <ButtonBase className={css.stretchLight} />
      <ButtonBase className={css.minimizeLight} />
```

closeLight -> Red Button
stretchLight -> Green Button
minimizeLight -> Yellow Button

Tho in styles they are styled correctly

**Comment by PuruVJ** [comment]
Feel free to rename the classes

**Comment by PuruVJ** [comment]
I have no idea which of these do what except for the red one. Use your judgement 😁

**Comment by PuruVJ** [comment]
Hi. Sorry for the inconvenience. I just merged a PR which changes TrafficLights component a bit. Could you pls git pull it and fix the merge conflicts, if any

**Comment by Deep-Codes** [comment]
Alright let me see 👀

**Comment by Deep-Codes** [comment]
@PuruVJ  there's a problem

PR merged: It's hiding icons

arent styles scoped?

<img width="342" alt="Screenshot 2021-04-16 at 12 22 20 AM" src="https://user-images.githubusercontent.com/61158210/114922874-d0ee2000-9e49-11eb-8e71-88a282767a22.png">

**Comment by PuruVJ** [comment]
Yes it is hiding styles for me too

**Comment by PuruVJ** [comment]
They are scoped if you use CSS modules

**Comment by PuruVJ** [comment]
Huh, it is CSS modules, but it is still hiding. Strange

**Comment by PuruVJ** [comment]
Oh wait, this lone svg is causing issues. This will not be scoped 
![image](https://user-images.githubusercontent.com/47742487/114923558-96d14e00-9e4a-11eb-8634-bdf6fe20259c.png)

**Comment by PuruVJ** [comment]
No issues, I'll scope it. No big deal :)

**Comment by PuruVJ** [comment]
Fixed. Will be live soon

**Comment by Deep-Codes** [comment]
Yeah this would solve it:

```scss
.container {
  display: inline-flex;
  align-items: center;
  gap: 0.45rem;

  height: 100%;

  &:hover .trafficLight svg {
    visibility: visible;
  }
}

.trafficLight svg {
  visibility: hidden;
}
```

or use visibility

**Comment by PuruVJ** [comment]
Fixed in #66

**Comment by PuruVJ** [comment]
Hi, Can I ask you your Twitter handle?

**Comment by Deep-Codes** [comment]
> Hi, Can I ask you your Twitter handle?

Yeah sure it's [@DeepankarBhade](https://twitter.com/DeepankarBhade)
