### ISSUE TITLE
Remove tippyjs from MenuBar and Action Center

### ISSUE THREAD

**Issue by PuruVJ** [PuruVJ/macos-web#69]
Currently, MenuBar, to show menus, uses TippyJS and lots of state management with Jotai. But that is quite slow.

Goal:
Remove TippyJS from the equation entirely.
Rely on CSS as much as possible, though using Jotai to show stuff actually seems like the best scenario here, as `:hover` will not work unidirectionally, that is, it will show as well as hide on hover and removed-hover, which we do not want.

Same goes for ActionCenter. Use same methods for it too

**Comment by Aslemammad** [comment]
I'm going to work on this issue, thanks.

**Comment by PuruVJ** [comment]
The files to look at: `MenuBar.tsx` and `Menu.tsx`, both in `TopBar` folder
