### ISSUE TITLE
Simulate updates via PWA

### ISSUE THREAD

**Issue by userquin** [PuruVJ/macos-web#7]
Hi @PuruVJ , this is a thing I want to include here, but first I will include on the vue 3 version via `vite-plugin-pwa` of course.

I know the updates on macosx comes from `AppStore`, but instead including right now the icon and the window for `AppStore`, we can for example just add the icon and some badge with number over it, and then when clicked simulate the update.

Once included on my vue 3 I can also add it here, since both repos will use vite.

**Comment by PuruVJ** [comment]
This is freaking great!!! Let's do this
