### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by Deep-Codes** [PuruVJ/macos-web#71]
I have a bare model of the `context menu` created.

I didn't use the API for `Menubar` to implement this, found it too complex 😅.

![github](https://user-images.githubusercontent.com/61158210/115059375-1a02aa80-9f04-11eb-870b-65fc81b768f9.gif)

let me know if you want this feature.

**Comment by PuruVJ** [comment]
Looks great. Can you push this code to your own fork's branch so I can take a look?

**Comment by Deep-Codes** [comment]
> Looks great. Can you push this code to your own fork's branch so I can take a look?

Yeah [Context Menu](https://github.com/Deep-Codes/macos-web/tree/context-menu)

This is the most bare model implementation haven't used `jotai` yet and code is janky 
Also why doesn't the hover work in the menu 👀

**Comment by PuruVJ** [comment]
The code seems fine to me. I kinda don't like the hard coded menu items, but who cares right now really, no point in having object-based/dynamic context menu until we have some apps 😉.

About the hoverable thing, it probably needs a sprinkle of z-index: 9999999 or something. Try that, and even if it doesn't work, no issues, I'll fix it by looking at the DOM 3D model.

Overall looks good to me. Please do send a PR
