### ISSUE TITLE
Tooltip in Dock

### ISSUE THREAD

**Issue by Deep-Codes** [PuruVJ/macos-web#74]
Very Simple Tooltip with Pure CSS

https://user-images.githubusercontent.com/61158210/115134112-1453b480-a02b-11eb-84b7-21b60e53b4bd.mp4

Let me know!

**Comment by PuruVJ** [comment]
This looks awesome. Did you make this with CSS only or was Tippy involved too?

Also, please do push to code to your own fork after doing a git pull, I wanna see the rough code.

**Comment by Deep-Codes** [comment]
> This looks awesome. Did you make this with CSS only or was Tippy involved too?
> 
> Also, please do push to code to your own fork after doing a git pull, I wanna see the rough code.

Only CSS 🚀

**Comment by PuruVJ** [comment]
This looks good. I relied on heavy JS libraries, but you show again what CSS can do. 

Can you move the tooltip to its own component, like a `DockTooltip` component, as well as the style too? And before that, please sync your fork with upstream, or you'll get the old obsolete component of the same name. 

Thanks :)

**Comment by Deep-Codes** [comment]
> This looks good. I relied on heavy JS libraries, but you show again what CSS can do.
> 
> Can you move the tooltip to its own component, like a `DockTooltip` component, as well as the style too? And before that, please sync your fork with upstream, or you'll get the old obsolete component of the same name.
> 
> Thanks :)

Wouldn't the moving styles to its own file cause a problem because it's dependent on `DockItem.module.scss` for the `hover` trigger or am i missing on something ?

**Comment by PuruVJ** [comment]
Good point. I dunno how to reference classes from other files.

No worries, we can always refactor later. Please make the PR
