### ISSUE TITLE
Bounce icon on app start

### ISSUE THREAD

**Issue by Bellisario** [PuruVJ/macos-web#94]
Can be very beautiful see macOS app bouncing when an app "starts"! :wink:

**Comment by PuruVJ** [comment]
Does that happen in real macOS? Got any clip to show that?

**Comment by Bellisario** [comment]
Yes, @PuruVJ, this is real... here is a video to disable it :laughing:: https://www.youtube.com/watch?v=w6vd6ow8r44

(I linked a video because I'm currently using a mac)
**P.S.:** I think in macOS Bigsur with M1 this is really a short while

**Comment by PuruVJ** [comment]
Ohh, that bounce. I think we can implement it, though it would be really short in our case. Maybe one bounce

**Comment by PuruVJ** [comment]
Now that code splitting and dynamic importing of apps is here, there's some delay when the app is loaded. By using Suspense, we can implement the bounce animation. 

This issue just became high priority. Will be worked on next.

**Comment by PuruVJ** [comment]
Fixed in https://github.com/PuruVJ/macos-web/commit/4936f58bec572f3983f683ef3cf8376795274c68
